# Generated by Django 5.1.6 on 2025-06-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_training_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='training_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
