# Generated by Django 5.1.6 on 2025-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_training_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tier',
            field=models.CharField(blank=True, choices=[('tier_1', 'Tier 1 (0-2 years)'), ('tier_2', 'Tier 2 (2-4 years)'), ('tier_3', 'Tier 3 (5-8 years)'), ('tier_4', 'Tier 4 (8+ years)')], help_text='Driver tier based on experience', max_length=10, null=True),
        ),
    ]
