# Generated by Django 5.0.4 on 2025-06-19 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0002_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_number', models.CharField(max_length=50)),
                ('bol_number', models.CharField(blank=True, max_length=50)),
                ('shipper', models.CharField(max_length=255)),
                ('receiver', models.CharField(blank=True, max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=50)),
                ('pickup_zip', models.CharField(max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=50)),
                ('delivery_zip', models.CharField(max_length=20)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cargo_description', models.TextField()),
                ('weight', models.IntegerField(help_text='Weight in pounds')),
                ('distance', models.IntegerField(blank=True, help_text='Distance in miles', null=True)),
                ('estimated_transit_time', models.IntegerField(blank=True, help_text='Time in hours', null=True)),
                ('pickup_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('hazmat', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=100)),
                ('dispatched_by', models.CharField(blank=True, max_length=255)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='drivers.driver')),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='vehicles.truck')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='companies.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.department')),
                ('destination_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_loads', to='companies.terminal')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.division')),
                ('origin_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_loads', to='companies.terminal')),
            ],
            options={
                'ordering': ['-pickup_date'],
                'unique_together': {('company', 'load_number')},
            },
        ),
        migrations.CreateModel(
            name='LoadDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('bol', 'Bill of Lading'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('photo', 'Photo'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='load_documents/')),
                ('uploaded_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loads.load')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('delay', 'Delay'), ('issue', 'Issue'), ('update', 'Update'), ('spill', 'Spill'), ('contamination', 'Contamination'), ('ncr', 'Non-Conformance Report')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('location_address', models.TextField(blank=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=50)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('reported_by', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loads.load')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
